### ISSUE TITLE
Unable to bind leader to SPC

### ISSUE THREAD

**Issue by marktran** [cofi/evil-leader#11]
With 0.2.1, I was able to bind leader to SPC via `(setq evil-leader/leader " ")`. This no longer works with the latest version.

**Comment by cofi** [comment]
I'm pretty sure this never worked because the leader key was always processed via `read-kbd-macro`. What you actually want is `(setq evil-leader/leader "SPC")`:

```
ELISP> (read-kbd-macro " ")
""
ELISP> (read-kbd-macro "SPC")
" "
```
