### ISSUE TITLE
Can't use m as leader?

### ISSUE THREAD

**Issue by mavenraven** [cofi/evil-leader#19]
I'm trying to use the letter m as my leader, but it's the only key that doesn't work for some reason.  I've tried:

```
(evil-leader/set-leader "m")
```

and

```
(evil-leader/set-leader "\155")
```

.

```
(read-kbd-macro "m")
```

returns "m", so that looks ok. Any ideas?

**Comment by cofi** [comment]
Sorry for the long delay.

The problem stems from `m` being also bound in the usual map the normal state. Which is now also overwritten.

Please try 0.4.2 it should resolve the issue.

**Comment by brabalan** [comment]
I had the same problem and I solved it this way:

```  emacs-lisp
(require 'evil-leader)
(define-key evil-normal-state-map "m" nil)
(evil-leader/set-leader "m")
(global-evil-leader-mode)
```
