### ISSUE TITLE
Evil-leader disabled upon reloading ~/.emacs

### ISSUE THREAD

**Issue by seanegoodwin** [cofi/evil-leader#20]
I have evil-leader enabled in my ~/.emacs. If I make a change (unrelated to evil/evil-leader) and reload the config file, evil-leader is always disabled and has to be manually invoked.

**Comment by cofi** [comment]
Hi,

How do you enable evil-leader and how do you reload your config?

Using

```
(global-evil-leader-mode)
```

to enable evil-leader does not toggle on a repeated evaluation.

**Comment by seanegoodwin** [comment]
That is how I enable evil leader. I reload .emacs with M-x load-file. I have also tried M-x eval-buffer and gotten the same results. 

I can get the behavior with [this](http://pastebin.com/x1rSVAYy) basic config.

**Comment by cofi** [comment]
Which Emacs version do you use? Older Emacsen - I think < 24.2 - would toggle the mode without an argument.

An explicit argument should help in that case

```
(global-evil-leader-mode 1)
```

I cannot replicate this behavior on a recent Emacs (24.3.1).

**Comment by seanegoodwin** [comment]
I seem to have found the problem (or at least a workaround). 

If I invoke evil-leader/set-leader after evil-mode, I get the previous behavior. If I invoke it before starting evil-mode, I don't.
