### ISSUE TITLE
how to load-file

### ISSUE THREAD

**Issue by pvinis** [cofi/evil-leader#30]
i have this

```
(evil-leader/set-key "rr" (lambda (arg)
         (load-file "~/.emacs.d/init.el")))
```

but it doesnt work. it gives me wrong type argument: commandp.
how can i fix that?

**Comment by cofi** [comment]
That's basic emacs stuff: You can only bind a command to a key. To make that lambda into a command, add the `interactive` form:

`````` elisp
(evil-leader/set-key "rr" (lambda (arg)
         (interactive)
         (load-file "~/.emacs.d/init.el")))```
``````

**Comment by pvinis** [comment]
thanks
