### ISSUE TITLE
can you create secondary leader key?

### ISSUE THREAD

**Issue by redguardtoo** [cofi/evil-leader#33]
secondary leader key could be bound to new commands.

I need this because my hotkeys is almost used up but I have still lots of commands to bind.

**Comment by noctuid** [comment]
@redguardtoo See [general.el](https://github.com/noctuid/general.el) which allows for an infinite number of leader keys. I just made it, so it's not on melpa yet though.

**Comment by redguardtoo** [comment]
@noctuid , great, Could  `general-default-keymap` be a list? I don't want to re-define key bindings in visual and normal state. Evil-leader supports this.

**Comment by noctuid** [comment]
@redguardtoo Sure, I've made an issue for it (noctuid/general.el#5). I'll implement this when I get the chance.
