### ISSUE TITLE
"Wrong type argument: commandp" in simple mapping

### ISSUE THREAD

**Issue by zzantares** [cofi/evil-leader#37]
Hi, I'm using `evil-leader` for a while now, but now that I want to add this mapping it doesn't work:

``` elisp
(evil-leader/set-key "ls" 'helm-buffer-list)
```

It gives `Wrong type argument: commandp, helm-buffer-list`, I don't know why with this particular function just doesn't work, seeing [helm-buffer-list definition](https://github.com/emacs-helm/helm/blob/master/helm-buffers.el#L285) it doesn't take any arguments.

Could anyone help, why this particular mapping is not working?

**Comment by oscarfv** [comment]
You can only bind keys to commands, which, roughly speaking, are functions with an `interactive` specification.

**Comment by zzantares** [comment]
Thanks, in deed was a dumb mistake of mine, the correct function (the `interactive` one) to use was `helm-buffers-list` with an extra `s`. Now it's working properly, sorry.
