### ISSUE TITLE
Also support <LocalLeader>

### ISSUE THREAD

**Issue by seschwar** [cofi/evil-leader#5]
Vim actually provides two leader keys: [`<Leader>`](http://vimdoc.sourceforge.net/htmldoc/map.html#mapleader) and [`<LocalLeader>`](http://vimdoc.sourceforge.net/htmldoc/map.html#maplocalleader) which can be set via [`mapleader`](http://vimdoc.sourceforge.net/htmldoc/map.html#mapleader) and [`maplocalleader`](http://vimdoc.sourceforge.net/htmldoc/map.html#maplocalleader) respectively.  And as the Vim documentation says:

> `<LocalLeader>` is just like `<Leader>`, except that it uses "maplocalleader" instead of "mapleader".  `<LocalLeader>` is to be used for mappings which are local to a buffer.

For example in Vim I have bound `<Leader>w` to `C-w` in order to avoid the control key.  This is a command which affect the whole Vim "frame"/tab.  I have also bound `<LocalLeader>s` to `:sort<CR>` in visual mode which only affects a single buffer.  While in this case I could bind both with the same leader key it is nice to have different leader keys for different scopes.  It would it make possible to have bindings like `<Leader>q` for `ZZ` and `<LocalLeader>q` for `:write|bdelete<CR>` for example.

**Comment by cofi** [comment]
I've pondered about this a while, but I won't put anymore significant work into evil-leader, so no.

The plan for the long term is to port vim-like keybindings (i.e. non-prefixfree and with timeouts) for evil. In addition to that moving <leader> into evil is planned - but by a another mechanism - so <localleader> could come along as well.
